# Generated by Django 4.2.7 on 2024-04-05 08:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptNote',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('problem_statement', models.TextField(blank=True, null=True)),
                ('main_object', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
