# Generated by Django 4.2.7 on 2024-04-08 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_conceptnote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConceptNote',
        ),
    ]
